spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-scanners}:${DB_PORT:5432}/${DB_NAME:bd_scanners}?ssl=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
service:
  signal-processing:
    url: ${SIGNAL_PROCESSING_URL:http://signal-processing-service:8000}
  log-service:
    ws-url: ${LOG_SERVICE_WS_URL:ws://log-service:8084/ws/internal/logs}
  notification-service:
    ws-url: ${NOTIFICATION_SERVICE_WS_URL:ws://notification-service:8085/ws/internal/notificaciones/estado-escaner}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:directory}:8761/eureka/
  instance:
    prefer-ip-address: true
